### ISSUE TITLE
Small challenge when using WinRT

### ISSUE THREAD

**Issue by oise** [halildurmus/win32#172]
I am having a small challenge using the WinRT APIs. I generated the dart projection for `Windows.Gaming.Input.IGamepad` using `winmd` and I get this

```
import 'dart:ffi';

import 'package:ffi/ffi.dart';
import 'package:win32/win32.dart';

/// @nodoc
const IID_IGamepad = '{BC7BB43C-0A69-3903-9E9D-A50F86A45DE5}';

typedef _get_Vibration_Native = Int32 Function(
    Pointer obj,
    Pointer<Uint32> value);
typedef _get_Vibration_Dart = int Function(
    Pointer obj,
    Pointer<Uint32> value);

typedef _put_Vibration_Native = Int32 Function(
    Pointer obj,
    Uint32 value
    );
typedef _put_Vibration_Dart = int Function(
    Pointer obj,
    int value
    );

typedef _GetCurrentReading_Native = Int32 Function(
    Pointer obj,
    Pointer<Uint32> result
    );
typedef _GetCurrentReading_Dart = int Function(
    Pointer obj,
    Pointer<Uint32> result
    );

/// {@category Interface}
/// {@category winrt}
class IGamepad extends IInspectable {
  // vtable begins at 6, ends at 8

  IGamepad(Pointer<COMObject> ptr) : super(ptr);

  int get Vibration {
    final retValuePtr = calloc<Uint32>();

    final hr = Pointer<NativeFunction<_get_Vibration_Native>>.fromAddress(
        ptr.ref.vtable.elementAt(6).value)
        .asFunction<_get_Vibration_Dart>()(ptr.ref.lpVtbl, retValuePtr);
    if (FAILED(hr)) throw WindowsException(hr);

    final retValue = retValuePtr.value;
    calloc.free(retValuePtr);
    return retValue;
  }

  set Vibration(int value) {
    final hr = Pointer<NativeFunction<_put_Vibration_Native>>.fromAddress(
        ptr.ref.vtable.elementAt(7).value)
        .asFunction<_put_Vibration_Dart>()(ptr.ref.lpVtbl, value);

    if (FAILED(hr)) throw WindowsException(hr);
  }

  int GetCurrentReading(Pointer<Uint32> result) =>
      Pointer<NativeFunction<_GetCurrentReading_Native>>.fromAddress(
          ptr.ref.vtable.elementAt(8).value)
          .asFunction<_GetCurrentReading_Dart>()(
          ptr.ref.lpVtbl, result);

}
```
When I call `createObject`  like this :
```
void main() {
  winrtInitialize();

// final object = CreateObject('Windows.Gaming.Input.IGamepad', IID_IGamepad);
  final object = CreateObject('Windows.Gaming.Input.Gamepad', IID_IGamepad);

  winrtUninitialize();
  print('Complete');
}
```

I get this error. 

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Error 0x80040154: Class not registered
#0      CreateObject (package:win32/src/winrt/winrt_helpers.dart:92:7)
#1      main (package:desktop_monitor/main.dart:19:18)
#2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:140:25)
#3      _rootRun (dart:async/zone.dart:1354:13)
#4      _CustomZone.run (dart:async/zone.dart:1258:19)
#5      _runZoned (dart:async/zone.dart:1788:10)
#6      runZonedGuarded (dart:async/zone.dart:1776:12)
#7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:133:5)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

I suppose i'm doing something wrong somewhere. Any nudge in the right direction would be much appreciated.

P.S this library rocks 👍

**Comment by timsneath** [comment]
It's not your fault at all. Windows Runtime API support is still very much a work in progress. 

`Gamepad` has a static `Gamepads` property that returns an enumeration of `GamePad` objects. So rather than calling `CreateObject` here, you call the static class. But this isn't wired up yet, so the primitives simply aren't there yet :( 

I'm sorry -- this is hard stuff, and I'm working on it slowly.

**Comment by timsneath** [comment]
I've now managed to wire up static WinRT objects, as shown here:
https://github.com/timsneath/win32/blob/main/lib/src/com/UserDataPaths.dart#L442

This example demonstrates this:
https://github.com/timsneath/win32/blob/main/example/appcontainer.dart

The generator isn't wired up to support this yet, but it should be possible to get `Gamepad` up and running using the same technique. I'll take a look as soon as I get the chance.
